ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "google_id" VARCHAR(255) UNIQUE;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "otp_code" VARCHAR(6);
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "otp_expires_at" TIMESTAMP;
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "refresh_token" VARCHAR(500);
